---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-deployment"
  labels:
    app: "{{ .Release.Name }}-deployment"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-deployment"
  strategy:
    type: {{ .Values.container.strategytype }}
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-deployment"
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.container.image }}
        imagePullPolicy: {{ .Values.container.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.container.ports.containerPort }}
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        resources:
          requests:
            memory: {{ .Values.container.resources.requests.memory }}
            cpu: {{ .Values.container.resources.requests.cpu }}
          limits:
            memory: {{ .Values.container.resources.limits.memory }}
            cpu: {{ .Values.container.resources.limits.cpu }}
